# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

flutter_library = '../flutter_library/'
load File.join(flutter_library, '.ios', 'Flutter', 'podhelper.rb')

target 'Calculator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	install_all_flutter_pods(flutter_library)

  # Pods for Calculator
	pod 'Firebase/Core'
	
end
